import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Button from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-auto w-[75%] min-w-2xl`}
      >
        <header className="w-full h-28 flex justify-between items-center">
          <nav>
            <ul className="flex gap-8 items-center">
              <li>A propos de moi</li>
              <li>Expériences</li>
              <li>Projets</li>
            </ul>
          </nav>

          <Button href="/">Contactez-moi</Button>
        </header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
